// <auto-generated />
namespace AYSAdalet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class vr3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vr3));
        
        string IMigrationMetadata.Id
        {
            get { return "202012251935027_vr3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
