// <auto-generated />
namespace AYSAdalet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Bilgi_Bilgisayar_Tablosu_Eklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bilgi_Bilgisayar_Tablosu_Eklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202012231613170_Bilgi_Bilgisayar_Tablosu_Eklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
