// <auto-generated />
namespace AYSAdalet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pgy2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pgy2));
        
        string IMigrationMetadata.Id
        {
            get { return "202012240825329_pgy2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
