// <auto-generated />
namespace AYSAdalet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bilgi_Talepv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bilgi_Talepv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202101052126124_bilgi_Talepv1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
