// <auto-generated />
namespace AYSAdalet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ver4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver4));
        
        string IMigrationMetadata.Id
        {
            get { return "202101062057299_ver4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
